/**
 * This file represents the root layout of the application.
 * It includes the global CSS import, the Navbar component, and the HTML structure.
 */

import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/Navbar';

/**
 * Metadata for the application.
 * This is used by Next.js to generate the HTML head section.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component.
 * This component wraps the application's content and provides a consistent layout.
 *
 * @param children - The React children to be rendered within the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='overflow-hidden'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}